### ISSUE TITLE
Missing File Issue After Fresh Clone

### ISSUE THREAD

**Issue by jackie-wylog** [iAmNaz/DecouplerKit#1]
![screen shot 2018-06-28 at 2 58 53 pm](https://user-images.githubusercontent.com/40656288/42019632-3252e8d6-7ae8-11e8-80a8-ad7cd0417a81.png)

**Comment by iAmNaz** [comment]
Please try the steps below:

rm -rf ./Pods
rm -rf ./Podfile.lock
pod install
